### ISSUE TITLE
Ameli Reyes Hernández. Línea del tiempo 

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-7-AmeliReyesHernandez#1]
[LINEA DEL TIEMPO DE LA WEB. Ameli Reyes.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-AmeliReyesHernandez/files/9793079/LINEA.DEL.TIEMPO.DE.LA.WEB.Ameli.Reyes.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
tiene 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
